android.enableAppCompileTimeRClass=true
android.useAndroidX=true
# Increase heap size for faster build
org.gradle.jvmargs=-Xmx4096m --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
# Enable caching and parallel execution
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.native.buildOutput=verbose
android.r8.maxWorkers=4
