# Imported from SUMHP cb8345501f3bf8c8f32c844b75751026e55801d1.
set(SUMHP_SOURCES
    src/core/command.cpp src/core/daemon.cpp src/core/log.cpp
    src/core/config.cpp src/core/runtime.cpp src/core/migration.cpp
    src/mount/backend.cpp src/mount/mount_fs.cpp src/mount/sumh.cpp
    src/mount/sumh_client.cpp src/mount/magic_mount.cpp
    src/mount/overlayfs.cpp src/mount/storage.cpp src/embedded.cpp)
add_library(ksud_sumhp_objs OBJECT ${SUMHP_SOURCES})
target_include_directories(ksud_sumhp_objs BEFORE PRIVATE include src ../src ../../..)
target_compile_options(ksud_sumhp_objs PRIVATE -fexceptions)
zysu_enable_clang_tidy(ksud_sumhp_objs CXX)
