#!/usr/bin/env python3
"""Generate compressed C++ arrays for ksud's embedded assets."""

import hashlib
import lzma
import re
import sys
import zlib
from pathlib import Path


LKM_SUFFIX = "_kernelsu.ko"
LKM_XZ_PRESET = 6
# Restrict embedding so stale binaries in a reused assets directory stay out.
RUNTIME_ASSETS = {"installer.sh", "shellrc.sh", "ksuinit"}


def to_c_identifier(name: str) -> str:
    """Convert a filename to a valid C identifier."""
    result = name.replace(".", "_").replace("-", "_")
    if result[0].isdigit():
        result = "_" + result
    return result


def cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def normalize_asset_data(filepath: Path, data: bytes) -> bytes:
    """Keep executable text assets usable regardless of checkout settings."""
    is_shell_script = filepath.suffix in {".sh", ".bash"} or (
        data.startswith(b"#!") and b"\0" not in data
    )
    if is_shell_script:
        return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return data


def byte_array(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <assets_dir> <output.cpp>")
        sys.exit(1)

    assets_dir = Path(sys.argv[1])
    output_file = Path(sys.argv[2])
    files = []
    if assets_dir.exists():
        files = sorted(
            path
            for path in assets_dir.iterdir()
            if path.is_file()
            and (path.name in RUNTIME_ASSETS or path.name.endswith(LKM_SUFFIX))
        )

    ordinary_assets = []
    lkm_assets = []
    lkm_raw = bytearray()
    for filepath in files:
        data = normalize_asset_data(filepath, filepath.read_bytes())
        identifier = to_c_identifier(filepath.name)
        if filepath.name.endswith(LKM_SUFFIX):
            kmi = filepath.name.removesuffix(LKM_SUFFIX)
            version = re.fullmatch(r"(?:android\d+-)?(\d+)\.(\d+)", kmi)
            if version is None or tuple(map(int, version.groups())) < (6, 1):
                raise SystemExit(
                    f"Unsupported LKM asset {filepath.name}: ZySU requires Linux 6.1 or newer"
                )
            offset = len(lkm_raw)
            lkm_raw.extend(data)
            lkm_assets.append(
                {
                    "name": filepath.name,
                    "identifier": identifier,
                    "offset": offset,
                    "size": len(data),
                    "sha256": hashlib.sha256(data).digest(),
                }
            )
        else:
            compressed = zlib.compress(data, level=9)
            ordinary_assets.append(
                {
                    "name": filepath.name,
                    "identifier": identifier,
                    "data": compressed,
                    "size": len(data),
                }
            )

    lkm_pack = b""
    if lkm_assets:
        lkm_pack = lzma.compress(
            bytes(lkm_raw),
            format=lzma.FORMAT_XZ,
            check=lzma.CHECK_CRC32,
            preset=LKM_XZ_PRESET,
        )

    output = [
        r'''// Auto-generated file - DO NOT EDIT
// Generated by embed_assets.py

#include "assets.hpp"
#include "defs.hpp"
#include "log.hpp"
#include "utils.hpp"
#include "xz_range.hpp"

#include <array>
#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <map>
#include <mbedtls/sha256.h>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>
#include <zlib.h>

namespace ksud {
'''
    ]

    ordinary_by_name = {asset["name"]: asset for asset in ordinary_assets}
    lkm_by_name = {asset["name"]: asset for asset in lkm_assets}
    for asset in ordinary_assets:
        array_name = f'asset_{asset["identifier"]}'
        output.append(f'// Asset: {asset["name"]}')
        output.append(byte_array(array_name, asset["data"]))
        output.append("")

    if lkm_assets:
        output.append("// Solid LKM pack; offsets refer to the uncompressed stream.")
        output.append(byte_array("asset_lkm_pack_xz", lkm_pack))
        output.append("")
        for asset in lkm_assets:
            output.append(
                byte_array(f'asset_{asset["identifier"]}_sha256', asset["sha256"])
            )
            output.append("")

    output.append(
        r'''enum class AssetCodec {
    Zlib,
    SolidXz,
};

struct AssetEntry {
    const char* name;
    const unsigned char* data;
    size_t size;
    size_t original_size;
    AssetCodec codec;
    uint64_t offset;
    uint64_t pack_original_size;
    const unsigned char* sha256;
};
'''
    )

    output.append(
        f"static const std::array<AssetEntry, {len(files) + 1}> asset_registry = {{{{"
    )
    for filepath in files:
        filename = filepath.name
        escaped = cpp_string(filename)
        if filename in ordinary_by_name:
            asset = ordinary_by_name[filename]
            identifier = asset["identifier"]
            output.append(
                f'    {{"{escaped}", asset_{identifier}, sizeof(asset_{identifier}), '
                f'{asset["size"]}, AssetCodec::Zlib, 0, 0, nullptr}},'
            )
        else:
            asset = lkm_by_name[filename]
            identifier = asset["identifier"]
            output.append(
                f'    {{"{escaped}", asset_lkm_pack_xz, sizeof(asset_lkm_pack_xz), '
                f'{asset["size"]}, AssetCodec::SolidXz, {asset["offset"]}, '
                f'{len(lkm_raw)}, asset_{identifier}_sha256}},'
            )
    output.append("    {nullptr, nullptr, 0, 0, AssetCodec::Zlib, 0, 0, nullptr}")
    output.append("}};\n")

    output.append(
        r'''const std::vector<std::string>& list_assets() {
    static const std::vector<std::string> names = [] {
        std::vector<std::string> result;
        result.reserve(asset_registry.size() - 1);
        for (const auto& entry : asset_registry) {
            if (entry.name == nullptr) break;
            result.emplace_back(entry.name);
        }
        return result;
    }();
    return names;
}

bool get_asset(const std::string& name, const uint8_t*& data, size_t& size) {
    for (const auto& entry : asset_registry) {
        if (entry.name == nullptr) break;
        if (name == entry.name) {
            data = entry.data;
            size = entry.size;
            return true;
        }
    }
    return false;
}

static bool file_sha256_matches(const std::string& path, const unsigned char* expected) {
    const int fd = open(path.c_str(), O_RDONLY | O_CLOEXEC);
    if (fd < 0) return false;

    mbedtls_sha256_context context;
    mbedtls_sha256_init(&context);
    bool ok = mbedtls_sha256_starts(&context, 0) == 0;
    std::array<unsigned char, 65536> buffer{};
    while (ok) {
        const ssize_t count = read(fd, buffer.data(), buffer.size());
        if (count > 0) {
            ok = mbedtls_sha256_update(&context, buffer.data(), static_cast<size_t>(count)) == 0;
            continue;
        }
        if (count < 0 && errno == EINTR) continue;
        ok = count == 0;
        break;
    }
    std::array<unsigned char, 32> digest{};
    if (ok) ok = mbedtls_sha256_finish(&context, digest.data()) == 0;
    mbedtls_sha256_free(&context);
    if (close(fd) != 0) ok = false;
    return ok && memcmp(digest.data(), expected, digest.size()) == 0;
}

bool copy_asset_to_file(const std::string& name, const std::string& dest_path) {
    const AssetEntry* entry = nullptr;
    for (const auto& candidate : asset_registry) {
        if (candidate.name == nullptr) break;
        if (name == candidate.name) {
            entry = &candidate;
            break;
        }
    }
    if (!entry) {
        LOGE("Asset not found: %s", name.c_str());
        return false;
    }

    unlink(dest_path.c_str());
    // Stream every asset directly to disk. Solid XZ extraction discards all
    // non-target LKM ranges before they reach this descriptor.
    const int fd = open(dest_path.c_str(), O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0644);
    if (fd < 0) {
        LOGE("Failed to open file for writing: %s (errno=%d: %s)", dest_path.c_str(), errno,
             strerror(errno));
        return false;
    }

    bool ok = false;
    int decompress_status = 0;
    if (entry->codec == AssetCodec::SolidXz) {
        decompress_status = zysu_unpack_xz_range_to_fd(
            entry->data, entry->size, entry->offset, entry->original_size,
            entry->pack_original_size, fd);
        ok = decompress_status == 0;
    } else {
        z_stream stream{};
        stream.next_in = const_cast<Bytef*>(entry->data);
        stream.avail_in = static_cast<uInt>(entry->size);
        decompress_status = inflateInit(&stream);
        ok = decompress_status == Z_OK;
        std::array<uint8_t, 65536> buffer{};
        while (ok && decompress_status != Z_STREAM_END) {
            stream.next_out = buffer.data();
            stream.avail_out = static_cast<uInt>(buffer.size());
            decompress_status = inflate(&stream, Z_NO_FLUSH);
            if (decompress_status != Z_OK && decompress_status != Z_STREAM_END) {
                ok = false;
                break;
            }
            const size_t produced = buffer.size() - stream.avail_out;
            size_t written = 0;
            while (written < produced) {
                const ssize_t count = write(fd, buffer.data() + written, produced - written);
                if (count > 0) {
                    written += static_cast<size_t>(count);
                    continue;
                }
                if (count < 0 && errno == EINTR) continue;
                ok = false;
                break;
            }
        }
        ok = ok && decompress_status == Z_STREAM_END && stream.total_out == entry->original_size;
        if (inflateEnd(&stream) != Z_OK) ok = false;
    }

    if (close(fd) != 0) ok = false;
    if (ok && entry->sha256 != nullptr)
        ok = file_sha256_matches(dest_path, entry->sha256);
    if (!ok) {
        LOGE("Asset extraction or verification failed for %s: %d", name.c_str(),
             decompress_status);
        unlink(dest_path.c_str());
    }
    return ok;
}

std::vector<std::string> list_supported_kmi() {
    std::vector<std::string> result;
    result.reserve(list_assets().size());
    for (const auto& name : list_assets()) {
        const char* suffix = "_kernelsu.ko";
        const size_t suffix_len = strlen(suffix);
        if (name.size() > suffix_len &&
            name.compare(name.size() - suffix_len, suffix_len, suffix) == 0) {
            result.push_back(name.substr(0, name.size() - suffix_len));
        }
    }
    return result;
}

int ensure_binaries(bool ignore_if_exist) {
    if (!ensure_dir_exists(BINARY_DIR)) {
        LOGE("Failed to create binary directory: %s", BINARY_DIR);
        return 1;
    }

    for (const auto& name : list_assets()) {
        // These payloads are extracted only by their dedicated install paths.
        if (name == "ksuinit" || name.find("_kernelsu.ko") != std::string::npos) {
            continue;
        }

        const std::string dest = std::string(BINARY_DIR) + name;
        (void)ignore_if_exist;
        if (!copy_asset_to_file(name, dest)) {
            LOGE("Failed to extract binary: %s", name.c_str());
            return 1;
        }
        chmod(dest.c_str(), 0755);
    }

    // Remove standalone su clients left by older compatibility modes.
    unlink((std::string(BINARY_DIR) + "su").c_str());
    unlink((std::string(WORKING_DIR) + "su").c_str());

    // Multi-call entries must remain links to the installed daemon.
    struct stat st{};
    if (stat(DAEMON_PATH, &st) == 0) {
        auto ensure_link = [](const char* link, const char* tag) {
            char cur[512];
            const ssize_t count = readlink(link, cur, sizeof(cur) - 1);
            if (count > 0) {
                cur[count] = '\0';
                if (strcmp(cur, DAEMON_PATH) == 0) return;
            }
            unlink(link);
            if (symlink(DAEMON_PATH, link) != 0) {
                LOGW("Failed to create %s symlink: %s", tag, strerror(errno));
            } else {
                LOGI("Created %s symlink: %s -> %s", tag, link, DAEMON_PATH);
            }
        };
        const std::string busybox_link = std::string(BINARY_DIR) + "busybox";
        ensure_link(DAEMON_LINK_PATH, "ksud");
        ensure_link(busybox_link.c_str(), "busybox");
    }

    return 0;
}

}  // namespace ksud
'''
    )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("\n".join(output), encoding="utf-8", newline="\n")

    print(f"Generated {output_file} with {len(files)} assets")
    for asset in ordinary_assets:
        print(
            f'  - {asset["name"]}: {len(asset["data"])} bytes '
            f'(original: {asset["size"]}, zlib)'
        )
    if lkm_assets:
        print(
            f"  - solid LKM pack: {len(lkm_pack)} bytes "
            f"(original: {len(lkm_raw)}, files: {len(lkm_assets)}, xz-{LKM_XZ_PRESET})"
        )
        for asset in lkm_assets:
            print(
                f'      {asset["name"]}: offset={asset["offset"]}, '
                f'size={asset["size"]}'
            )


if __name__ == "__main__":
    main()
